# Generated by Django 4.2.7 on 2024-01-16 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('software', '0002_comment_text_project_author_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='issue',
            name='attributed_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attributed', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(default='', max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(default=[], related_name='contributor_list', through='software.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
